-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghNA8gHk/HuV3qNfx
wnfAdiMPpaf4ppDn/7Zj438Yw9CgCgYIKoZIzj0DAQehRANCAARs/s6XTbyw2JkA
EMpXDKw0FwPDGKXNDvRYQ3uJzNkU0DQSL+Y3kVVZv2J/FOrhJcGgAs7MczZRJ9/T
r0XCmZBL
-----END PRIVATE KEY-----